#!/bin/bash

REPO=http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.26.msi
REPODIR=$(dirname $(realpath $0))/../repos/gtksharp

error()
{
    echo "$(date "+%F@%T") :: $1" 1>&2
    exit 1
}

report()
{
    echo "$(date "+%F@%T") :: $1"
}

download()
{
	mkdir -p ${REPODIR}
	report "Downloading GTK# for Windows"
	wget --quiet -O ${REPODIR}/gtksharp.msi ${REPO}
}

clean()
{
	pushd ${REPODIR}
	report "Deleting interstitial output"
	rm -rf	${REPODIR}/gtksharp
	popd
}

build()
{
	pushd ${REPODIR}
	report "Unpacking GTK# for Windows"
	msiexec /a gtksharp.msi /qb TARGETDIR=gtksharp
	popd
}

install()
{
	pushd ${REPODIR}
	popd
}

prerequisites()
{
	which msiexec 2>/dev/null || error "*** msiexec is not in \$PATH ***"
}

$@
