#!/bin/bash

REPO=http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.26.msi
REPODIR=$(dirname $(realpath $0))/../repos/gtksharp

error()
{
    echo "$(date "+%F@%T") :: $1" 1>&2
    exit 1
}

report()
{
    echo "$(date "+%F@%T") :: $1"
}

download()
{
	mkdir -p ${REPODIR}
	if [ ! -d "${REPODIR}/lessmsi" ]
		then report "Downloading LessMSIerables"
		wget --quiet -O ${REPODIR}/lessmsi.zip https://github.com/activescott/lessmsi/releases/download/v1.2.0/lessmsi-v1.2.0.zip
		mkdir -p ${REPODIR}/lessmsi
		unzip -d ${REPODIR}/lessmsi ${REPODIR}/lessmsi.zip
		chmod a+x ${REPODIR}/lessmsi/*.exe ${REPODIR}/lessmsi/*.dll
	fi
	report "Downloading GTK# for Windows"
	wget --quiet -O ${REPODIR}/gtksharp.msi ${REPO}
}

clean()
{
	pushd ${REPODIR}
	report "Deleting interstitial output"
	rm -rf	${REPODIR}/gtksharp
	popd
}

build()
{
	pushd ${REPODIR}
	report "Unpacking GTK# for Windows"
	mkdir -p gtksharp
	pushd lessmsi
	./lessmsi.exe x ../gtksharp.msi
	mv gtksharp ..
	popd
	popd
}

install()
{
	pushd ${REPODIR}
	popd
}

prerequisites()
{
	which msiexec 2>/dev/null || error "*** msiexec is not in \$PATH ***"
}

$@
