#!/bin/bash

REPO=${2:-"http://download.mono-project.com/archive/3.10.0/macos-10-x86/MonoFramework-MDK-3.10.0.macos10.xamarin.x86.pkg"}
REPODIR=$(dirname $(realpath $0))/../repos/managed-components

error()
{
    echo "$(date "+%F@%T") :: $1" 1>&2
    exit 1
}

report()
{
    echo "$(date "+%F@%T") :: $1"
}

download()
{
	mkdir -p ${REPODIR}
	report "Downloading Xar"
	wget --quiet -O ${REPODIR}/xar.tar.gz https://xar.googlecode.com/files/xar-1.5.2.tar.gz || error "*** Could not download Xar ***"
	report "Downloading Mono MDK for Mac"
	wget --quiet -O ${REPODIR}/mono.xar ${REPO}
}

clean()
{
	pushd ${REPODIR}
	report "Deleting interstitial output"
	rm -rf	${REPODIR}/mono-mac \
		${REPODIR}/xar \
		${REPODIR}/Distribution \
		${REPODIR}/mono.pkg \
		${REPODIR}/Resources \
		${REPODIR}/Library \
		${REPODIR}/../../tmp/mono-mac
	popd
}

build()
{
	pushd ${REPODIR}
	if [ ! -x "${REPODIR}/xar/src/xar" ]
		then report "Building Xar"
		mkdir -p xar
		tar xf xar.tar.gz -C xar/ --strip-components=1
		pushd xar/
		./configure
		make
		popd
	fi
	report "Unpacking Mono for Mac"
	xar/src/xar -x -f mono.xar
	zcat mono.pkg/Payload | bsdcpio -i
	mv Library/Frameworks/Mono.framework/Versions/3.* mono-mac
	popd
}

install()
{
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/ironpython				${REPODIR}/../../tmp/mono/lib/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/ironruby					${REPODIR}/../../tmp/mono/lib/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/boo					${REPODIR}/../../tmp/mono/lib/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/xsp					${REPODIR}/../../tmp/mono/lib/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/boo					${REPODIR}/../../tmp/mono/lib/mono/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/Microsoft*				${REPODIR}/../../tmp/mono/lib/mono/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/monodroid				${REPODIR}/../../tmp/mono/lib/mono/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/monotouch				${REPODIR}/../../tmp/mono/lib/mono/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/nuget				${REPODIR}/../../tmp/mono/lib/mono/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/portable*				${REPODIR}/../../tmp/mono/lib/mono/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/Reference*				${REPODIR}/../../tmp/mono/lib/mono/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/gac/FSharp.Core/4.3.1.0__b03f5f7f11d50a3a/FSharp*				${REPODIR}/../../tmp/mono/lib/mono/4.5/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/4.5/Microsoft.VisualBasic.dll	${REPODIR}/../../tmp/mono/lib/mono/4.5/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/4.5/Mono.Cecil.VB*			${REPODIR}/../../tmp/mono/lib/mono/4.5/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/4.5/Mono.WebServer2.dll		${REPODIR}/../../tmp/mono/lib/mono/4.5/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/4.5/vbnc.*				${REPODIR}/../../tmp/mono/lib/mono/4.5/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/4.5/xsp4.exe				${REPODIR}/../../tmp/mono/lib/mono/4.5/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/4.0/fs*.exe				${REPODIR}/../../tmp/mono/lib/mono/4.0/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/4.0/FSharp*				${REPODIR}/../../tmp/mono/lib/mono/4.0/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/4.0/Microsoft.VisualBasic.dll	${REPODIR}/../../tmp/mono/lib/mono/4.0/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/4.0/Microsoft*FSharp.Targets		${REPODIR}/../../tmp/mono/lib/mono/4.0/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/4.0/policy*FSharp*dll		${REPODIR}/../../tmp/mono/lib/mono/4.0/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/2.0/FSharp*				${REPODIR}/../../tmp/mono/lib/mono/2.0/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/2.0/Microsoft.VisualBasic.dll	${REPODIR}/../../tmp/mono/lib/mono/2.0/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/2.0/Mono.WebServer2.dll		${REPODIR}/../../tmp/mono/lib/mono/2.0/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/2.0/policy*FSharp*dll		${REPODIR}/../../tmp/mono/lib/mono/2.0/
	rsync -a --copy-links ${REPODIR}/mono-mac/lib/mono/2.0/xsp2.exe				${REPODIR}/../../tmp/mono/lib/mono/2.0/
	rsync -a --copy-links ${REPODIR}/mono-mac/bin/ir*					${REPODIR}/../../tmp/mono/bin/
	rsync -a --copy-links ${REPODIR}/mono-mac/bin/ipy*					${REPODIR}/../../tmp/mono/bin/
	rsync -a --copy-links ${REPODIR}/mono-mac/bin/fsharp*					${REPODIR}/../../tmp/mono/bin/
	rsync -a --copy-links ${REPODIR}/mono-mac/bin/xsp*					${REPODIR}/../../tmp/mono/bin/
	rsync -a --copy-links ${REPODIR}/mono-mac/bin/boo*					${REPODIR}/../../tmp/mono/bin/
	rsync -a --copy-links ${REPODIR}/mono-mac/bin/nuget					${REPODIR}/../../tmp/mono/bin/
	pushd ${REPODIR}/../../tmp/mono/bin
	rm -f xsp
	for i in ir ir64 irw irw64 xsp2 xsp4 booc booi booish fsharpc fsharpi fsharpiAnyCpu nuget ipy ipy64 ipyw ipyw64
		do sed -i 's#/Library.*mono #\"\$\{BASH_SOURCE%/\*\}\"/mono #' $i
		sed -i 's#/Library.*cli #\"\$\{BASH_SOURCE%/\*\}\"/cli #' $i
		if [ -n "$(grep -ho '[\" ]/Library.*\.exe' $i)" ]
			then EXENAME=$(basename `grep -ho -m 1 '[\" ]/Library.*\.exe' $i | sed 's/^\"//'`)
			RUNTIME=$(dirname `grep -ho -m 1 '[\" ]/Library.*\.exe' $i` | sed 's/^\"//' | sed 's#/Library.*/[0-9]\+\.[0-9]\+\.[0-9]\+/lib/##' | sed '/^mono\//! s#^#..\\\\#' | sed 's#^mono/##')
			sed "s#@@RUNTIME@@#${RUNTIME}\\\\#g" ${REPODIR}/../../resources/wrapper.bat > $i.bat
			sed -i "s#@@COMMAND@@#${EXENAME}#g" $i.bat
			sed -i 's#/#\\#g' $i.bat
		fi
		sed -i 's#/Library.*/[0-9]\+\.[0-9]\+\.[0-9]\+/lib/#\"\$\(cygpath -w \"\$\{BASH_SOURCE%/\*\}\"/../lib/\)\"#g#' $i
		sed -i 's#\"\"#\"#g' $i
		sed -i 's#)\"#)#g' $i
		sed -i 's#exe #exe\" #' $i
		sed -i 's#basename \$0#basename \"\$0\"#' $i
	done
	cp xsp4 xsp
	cp xsp4.bat xsp.bat
	chmod a+x *
	cd ..
	for i in lib/mono/boo/*.dll lib/mono/4.5/Mono.Cecil.VB*.dll lib/mono/*/Microsoft.VisualBasic.dll lib/mono/*/xsp*.exe lib/mono/*/FSharp*.dll lib/mono/*/Mono.WebServer*.dll
		do bin/gacutil -i $i
	done
	rsync -a --copy-links lib/mono/2.0/FSharp.Core.*data lib/mono/gac/FSharp.Core/2.3.0.0__*/
	rsync -a --copy-links lib/mono/4.0/FSharp.Core.*data lib/mono/gac/FSharp.Core/4.3.0.0__*/
	rsync -a --copy-links lib/mono/4.5/FSharp.Core.*data lib/mono/gac/FSharp.Core/4.3.1.0__*/
	rsync -a --copy-links lib/mono/monodroid/FSharp.Core.*data lib/mono/gac/FSharp.Core/2.3.98.1__*/
	rsync -a --copy-links lib/mono/portable259/FSharp.Core.*data lib/mono/gac/FSharp.Core/3.259.3.1__*/
	rsync -a --copy-links lib/mono/portable259/FSharp.Core.*data lib/mono/gac/FSharp.Core/3.78.3.1__*/
	rsync -a --copy-links lib/mono/portable47/FSharp.Core.*data lib/mono/gac/FSharp.Core/2.3.5.0__*/
	rsync -a --copy-links lib/mono/portable7/FSharp.Core.*data lib/mono/gac/FSharp.Core/3.3.1.0__*/
	popd
}

prerequisites()
{
	which bsdcpio		2>/dev/null || error "*** bsdcpio is not in \$PATH ***"
	which wget 		2>/dev/null || error "*** wget is not in \$PATH ***"
	which xml2-config	2>/dev/null || error "*** xml2-config is not in \$PATH ***"
	if [ ! -e "/usr/include/openssl/crypto.h" ]
		then error "*** openssl-devel is not installed ***"
	fi
}

$@
