#!/bin/sh
echo > /usr/share/gnome/autostart/gnome-do.desktop << EOF
[Desktop Entry]
Name=GNOME Do
Type=Application
Exec=gnome-do --quiet
Terminal=false
Icon=gnome-run
Comment=Do things quickly with objects in your GNOME desktop enviornment
Categories=Utility;
OnlyShowIn=GNOME;
EOF
