GARNAME    = debs
CATEGORIES = maemo/tasks
GARVERSION = $(GARMONO_VERSION)

DEPENDS  = maemo/debs/mono

DESCRIPTION = Meta package to generate Mono packages for Maemo
define BLURB
 This meta package generates Mono packages (aka .deb) for Maemo platform, all 
 library and dependencies is also generated.
endef

include ../../../gar.mk

