// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MoonlightStatus {
    
    public partial class MoonlightStatus {
        protected System.Web.UI.HtmlControls.HtmlGenericControl MoonContent;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
