CLEAR =\e[0;0m
BOLD=\e[1m
ULINE=\e[4m
REVERSE=\e[7m

BLACK=\e[30m
RED=\e[31m
GREEN=\e[32m
YELLOW=\e[33m
BLUE=\e[34m
VIOLET=\e[35m
CYAN=\e[36m
WHITE=\e[37m

BLACKBG=\e[40m
REDBG=\e[41m
GREENBG=\e[42m
YELLOWBG=\e[43m
BLUEBG=\e[44m
VIOLETBG=\e[45m
CYANBG=\e[46m
WHITEBG=\e[47m

NAMECOLOR ?= $(BOLD)$(YELLOW)
STAGECOLOR ?= $(BOLD)$(GREEN)
ERRORCOLOR ?= $(BOLD)$(REDBG)$(WHITE)
SUCCESSCOLOR ?= $(NORMAL)$(GREEN)
WORKCOLOR ?= $(NORMAL)$(CYAN)
NORMALCOLOR ?= $(CLEAR)

main_ANNOUNCECOLOR ?= $(BOLD)$(WHITE)
singularity_ANNOUNCECOLOR ?= $(BOLD)$(CYAN)
build_ANNOUNCECOLOR ?= $(BOLD)$(BLUE)
rootbin_ANNOUNCECOLOR ?= $(NORMAL)$(RED)
lnximg_ANNOUNCECOLOR ?= $(NORMAL)$(VIOLET)

ANNOUNCECOLOR=$($(DESTIMG)_ANNOUNCECOLOR)
