GARNAME = glib
GARVERSION = 2.8.6
CATEGORIES = mono-devkit
DISTFILES = $(GARNAME)-$(GARVERSION).tar.bz2

PATCHFILES =

LIBDEPS =
DEPENDS = 

DESCRIPTION = $(GARNAME)

DEBIAN_PACKAGES = 

define BLURB
 # FIXME: blurb goes here
endef

CONFIGURE_ARGS = --prefix=$(prefix)
BUILD_ARGS = 

CONFIGURE_SCRIPTS = $(WORKSRC)/configure
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk
