#!/bin/bash

DEVKIT_PREFIX=/scratchbox/devkits/mono

target=$(grep ^SBOX_CPU= /targets/links/scratchbox.config | cut -d= -f2)
if [ "$target" = "arm" ]; then
	export SBOX_UNAME_MACHINE=arm
fi

export MONO_GAC_PREFIX=/usr
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig:$DEVKIT_PREFIX/lib/pkgconfig
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DEVKIT_PREFIX/lib:$DEVKIT_PREFIX/lib/glib

