#!/bin/sh
#
# Usage: setup-machine host login branch
# 
# sample: setup-machine amd-mono nbuilder trunk
#
login=$2
host=$1
branch=$3

fq_host=$host.boston.ximian.com

if test x$branch = x; then
	echo Usage is: setup-machine host login trunk
	exit 1
fi

if test '!' -f config/$host; then
	echo No config file for host $host
	exit 1
fi

echo "Setting up $host"

branch=`echo $branch | sed 's#/#-#g'`

echo -n "     Copying files..."
ssh $login@$fq_host "echo $branch > BRANCH; mkdir -p $branch"
scp -qpr scripts/* $login@$fq_host:$branch
scp -q ~/.ssh/builder-id-dsa $login@$fq_host:.ssh/id_dsa
scp -q config/$host $login@$fq_host:buildbot-config
echo "  ok."

echo -n "     Starting server..."
ssh $login@$fq_host "chmod 700 ~/.ssh; chmod 600 ~/.ssh/*; cd $branch; sh connect" &> /dev/null
echo "  ok."
