#!/bin/sh -x
if [ -d /Library/Frameworks/Mono.framework/Commands ]; then
cd /Library/Frameworks/Mono.framework/Commands
for i in `ls -al | grep -v .exe | awk '{print $9}'`; do
    echo "${i}"
    ln -sf $PWD/${i} /usr/bin/${i}
done;
else
    echo "/Library/Frameworks/Mono.framework/Commands does not exist"
    echo "Can not create links to /usr/bin."
fi

if [ -d /Library/Frameworks/Mono.framework/Versions/Current ]; then
cd /Library/Frameworks/Mono.framework/Versions/Current/man
for i in man*; do
   (cd ${i};
   for j in *; do
     ln -sf $PWD/${j} /usr/share/man/${i}/${j}
   done)
done
fi
