#!/bin/sh
# Toggle build bot on/off or display status
# modifies config.py

if [ "$1" == "on" ]; then
   sed -i -e 's/^td_active =.*$/td_active = True/g' \
          -e 's/^sd_active =.*$/sd_active = True/g' \
          -e 's/^sync_active =.*$/sync_active = True/g' config.py
   echo "Buildbot now ON"
elif [ "$1" == "off" ]; then
   sed -i -e 's/^td_active =.*$/td_active = False/g' \
          -e 's/^sd_active =.*$/sd_active = False/g' \
          -e 's/^sync_active =.*$/sync_active = False/g' config.py
   echo "Buildbot now OFF"
elif [ "$1" == "status" ]; then
   if grep "td_active = True" config.py > /dev/null 2>&1; then
      echo "Buildbot is ON"
   else
      echo "Buildbot is OFF"
   fi
else
   echo "Usage:"
   echo
   echo "   $0 on|off|status"
   echo
fi

