#!/usr/bin/perl

if ($#ARGV < 2){
   die "Usage: generate-static output_file TARGET_CAPTION content [tocfile [headfile [prologuefile]]]";
}
open OUTPUT, ">$ARGV[0]";
$caption = $ARGV [1];
open CONTENT, $ARGV [2] || die "Can not open content file";

if ($#ARGV >= 3){
    if ($ARGV [3] ne "NONE"){
	$toc = 1;
	open TOC, $ARGV[3] || die "Can not open $ARGV[3]\n";
    }
}

if ($#ARGV >= 4){
    if ($ARGV [4] ne "NONE"){
	$head = 1;
	print "Using HEAD from $ARGV[4]\n";
	open HEAD, $ARGV[4] || die "Can not open head file $ARGV[4]\n";
    }
}

if ($#ARGV >= 5){
    open PROLOGUE, $ARGV[5] || die "No prologue found $ARGV[5]\n";
    print OUTPUT <PROLOGUE>;
    
}
 
open TEMPLATE, "TemplateExport.html" || die "Can not open TemplateExport.html";
$scanning_for_header = 1;
while (<TEMPLATE>){
    if (/<title>TemplateExport - Mono<\/title>/){
	print OUTPUT "<title>$caption - Mono</title>\n";
	next;
    }
    if (/<!--BEGIN PAGE TITLE--><!--END PAGE TITLE-->/){
	if ($caption eq "Contact"){
	    $t = "Contact Mono at Novell";
	} else {
	    $t = $caption;
	}
	$_ =~ s/<!--BEGIN PAGE TITLE--><!--END PAGE TITLE-->/$t/;
    }

    if ($head && /<\/head>/){
	print OUTPUT <HEAD>;
    }

    if ($scanning_for_header && /<div id="header">/){
	$in_header = 1;
    } 
    
    if ($in_header){
	if (/<\/UL>/){
	    $in_header = 0;
	    $scanning_for_header = 0;
	}
	
	$_ =~ s/ class="current_page_item"//;
	
	if (/<li.*>$caption</){
	    $_ =~ s/id="/class="current_page_item" id="/;
	}
    } 
    
    # if we got a toc, we need to remove the `wide' class which hides the TOC
    if (defined ($toc) && /div.*class="wide">/){
	$_ =~ s/class="wide"//;
    }
    
    if (/<!-- BEGIN MAIN CONTENT -->/){
	print OUTPUT <CONTENT>;
	do {
	    $_ = <TEMPLATE>;
	} while (!/<!-- END MAIN CONTENT -->/);
	next;
    }
    if ($toc && /<!-- BEGIN SIDE CONTENT -->/){
	print OUTPUT <TOC>;
	do {
	    $_ = <TEMPLATE>;
	} while (!/<!-- END SIDE CONTENT -->/);
	next;
    }
    
    print OUTPUT;
}

close OUTPUT;
