#! /bin/bash

. $HOME/buildbot-config
. ./shared-vars

rm -f /tmp/buildflag-$USER-`hostname`
cd mono
error_exit() 
{ 
	echo error 
	exit 1 
}

if uname | grep CYGWIN; then
    echo Windows Build.
    cd ..
    bash mono-build-w32.sh || error_exit
else
    echo "Calling autogen.sh --with-preview=yes --prefix=/mono"
    sh autogen.sh --with-preview=yes --prefix=$prefix || { echo "errors"; exit 1; }
    
    echo "Calling make"
    make MCS_FLAGS='-debug' || error_exit
    
    echo "Calling make install"
    make install || error_exit
fi
    
touch /tmp/buildflag-$USER-`hostname`

