#! /bin/bash
if test '!' -f /tmp/buildflag-$USER-`hostname`; then
	echo Build failed, skipping extras
	exit 1
fi
. shared-vars

echo Running: $extra_script

export PATH=$prefix/bin:$PATH
unset MONO_PATH

$extra_script

exit 0
