GARNAME    = devkit
CATEGORIES = maemo/task
GARVERSION = $(GARMONO_VERSION)

DEPENDS  = maemo/devkit/mono
DEPENDS += maemo/devkit/gtk-sharp
#DEPENDS += maemo/devkit/maemo-sharp
DEPENDS += maemo/devkit/environment

DESCRIPTION = Mono scratchbox devkit
define BLURB
 This meta package generates Mono devkit for Maemo.
endef

include ../../../gar.mk

