#!/bin/bash -e
BASEURL="http://build.mono.lab.novell.com/builds"
TYPE="HEAD"
TYPE="RELEASE"
NAME="novell-moonlight"
PACKAGE="moon-branch"


if [ -z "$1" ]; then
	echo "Please supply a revision"
	exit 1
else
	REVISION="$1"
fi

if [ "$REVISION" == "clean" ]; then
	rm -rf novell-moonlight*
	exit
fi

for version in "1.0.1"; do
	for arch in "i586" "x86_64"; do
		for media in ""; do

			DISTRO="suse-103-$arch"
			echo "Fetching $NAME$media-$version-$arch.xpi"
			echo "curl -o $NAME$media-$version-$arch.xpi $BASEURL/$TYPE/$DISTRO/$PACKAGE/$REVISION/files/steps/plugin-$version$media/novell-moonlight.xpi"
			curl -o "$NAME$media-$version-$arch.xpi" "$BASEURL/$TYPE/$DISTRO/$PACKAGE/$REVISION/files/steps/plugin-$version$media/novell-moonlight.xpi"

			# Prep non-ffmpeg xpis for signing
			if [ "$media" == "" ]; then  
				echo "Prepping $NAME-$version-$arch"
				mkdir "$NAME-$version-$arch"
				unzip -d "$NAME-$version-$arch" "$NAME-$version-$arch.xpi"
				rm "$NAME-$version-$arch.xpi"
			else
				echo "Not prepping $NAME$media-$version-$arch"
			fi
			
		done
	done
done
