#!/bin/sh -x

if [ -d /Library/Frameworks/Mono.framework/Commands ]; then
    cd /Library/Frameworks/Mono.framework/Commands
    for i in *; do
	# Only create a symlink if there isn't a file there
	if test ! -e "/usr/bin/${i}"; then
        	echo "${i}"
	        ln -sf "$PWD/${i}" "/usr/bin/${i}"
	fi
    done;
else
    echo "/Library/Frameworks/Mono.framework/Commands does not exist"
    echo "Can not create links to /usr/bin."
fi

if [ -d /Library/Frameworks/Mono.framework/Versions/Current ]; then
    cd /Library/Frameworks/Mono.framework/Versions/Current/share/man
    for i in man*; do
       (cd ${i};
       for j in *; do
         if test ! -e "/usr/share/man/${i}/${j}"; then
           ln -sf "$PWD/${j}" "/usr/share/man/${i}/${j}"
         fi
       done)
    done

    cd /Library/Frameworks/Mono.framework/Versions/Current/etc
    # Make sure we run the files we lay down, and not other stuff installed on the system
    export PATH=/Library/Frameworks/Mono.framework/Versions/Current/bin:$PATH
    # gtk+ setup
    gdk-pixbuf-query-loaders > gtk-2.0/gdk-pixbuf.loaders
    # pango setup
    mkdir -p pango
    pango-querymodules >  pango/pango.modules
fi

# Mono framework should be owned by root
chown -R root:admin /Library/Frameworks/Mono.framework
