#!/usr/bin/env python

# We support 10.4 and up

# gtk+ build notes:
#
#http://developer.imendio.com/projects/gtk-macosx/build-instructions
#http://developer.imendio.com/svn/gtk-osx-build/gtk-osx.modules


BUILD_HOSTS = ['macos-10-ppc', 'macos-10-x86']

prefix = "/Library/Frameworks/Mono.framework/Versions/Current"

packages = [
	{
		'name': 'pkg-config', 
		'source': 'http://pkgconfig.freedesktop.org/releases/pkg-config-0.25.tar.gz',
		'post':"""
			# Configure shell wrapper for pkg-config so it will look for .pc files when installed (#79671)
			cd /tmp/install/bin
			mv pkg-config pkg-config.bin
			cat <<EOF > pkg-config
#!/bin/sh
if [ -z "\$PKG_CONFIG_LIBDIR" ]; then
	export PKG_CONFIG_LIBDIR=/tmp/install/lib/pkgconfig:/tmp/install/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
fi
/tmp/install/bin/pkg-config.bin "\$@"
EOF
			chmod 755 pkg-config
			"""
	},
	{
		'name': 'gettext', 
		'source': 'http://ftp.gnu.org/pub/gnu/gettext/gettext-0.18.1.1.tar.gz',
		'post':"""
			# Save msgfmt, as this is needed for building glib
			#  we also need msgmerge for intltool... (monodevelop)
			rm -Rf /tmp/temp_install
			mkdir -p /tmp/temp_install/bin
			cd /tmp/install/bin
			mv xgettext msgfmt msgmerge /tmp/temp_install/bin
			cd -

			rm -Rf /tmp/install/bin/*
			rm -Rf /tmp/install/share/doc
			rm -Rf /tmp/install/share/emacs
			rm -Rf /tmp/install/share/gettext

			mv /tmp/temp_install/bin/* /tmp/install/bin
			"""
	},
	{
		'name': 'glib', 
		'source': 'http://ftp.gnome.org/pub/gnome/sources/glib/2.24/glib-2.24.1.tar.bz2',
		'build':
			"""set -x
			find . -iname "makefile\.in" | xargs sed -i -e 's@which[[:space:]]*gtkdoc-rebase@/usr/bin/false@'
			LDFLAGS="$LDFLAGS -lresolv" ./configure --prefix=/tmp/install
			make || exit 1
			make install || exit 1
			""",
		'post':"""
			# glib-mkenums is required for pango, maybe others
			#rm -Rf /tmp/install/bin/*
			"""
	},
	{
		'name': 'jpeg', 
		'version': '8',
		'source': 'http://www.ijg.org/files/jpegsrc.v8b.tar.gz',
		'build':
			"""ln -s `which glibtool` ./libtool

			./configure --enable-shared --enable-static --enable-freetype --prefix=/tmp/install
			make || exit 1
			mkdir -p /tmp/install/lib
			mkdir -p /tmp/install/include
			make install || exit 1
			"""
	},
	{
		'name': 'tiff', 
		'source': 'http://dl.maptools.org/dl/libtiff/tiff-3.8.2.tar.gz',
		'build':
			"""
			./configure --prefix=/tmp/install --mandir=/tmp/install/share/man \
				--with-jpeg-include-dir=/tmp/build_deps/include --with-jpeg-lib-dir=/tmp/build_deps/lib

			# 3.8.2's libtool didn't like the sysroot for building on 10.3
			rm libtool
			ln -s `which glibtool` ./libtool

			make || exit 1
			cd libtiff
			make install || exit 1
			"""
	},
	{
		'name': 'libpng',
		'source': 'http://voxel.dl.sourceforge.net/project/libpng/03-libpng-previous/1.2.44/libpng-1.2.44.tar.bz2',
		#'source': 'ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng-1.4.0.tar.bz2',
		'post':"""
			rm -Rf /tmp/install/bin/*
			"""
	},
	{
		'name': 'giflib', 
                'source': 'http://cdnetworks-us-1.dl.sourceforge.net/project/giflib/giflib%204.x/giflib-4.1.6/giflib-4.1.6.tar.bz2',
		'post':"""
			rm -Rf /tmp/install/bin/*
			"""
	},
	# Include our own because 10.4 and 10.5 ppc have differing expat versions
	{
		'name': 'expat', 
		'source': 'http://cdnetworks-us-1.dl.sourceforge.net/project/expat/expat/2.0.1/expat-2.0.1.tar.gz',
		'build': """
			./configure --prefix=/tmp/install 
			make
			make install
			""",
		'post':"""
			rm -Rf /tmp/install/bin
			rm -Rf /tmp/install/man
			""",
	},
	{
		'name': 'pixman', 
		'source': 'http://cairographics.org/releases/pixman-0.18.2.tar.gz',
	},
	{
		'name': 'freetype',
		'source': 'http://download.savannah.gnu.org/releases/freetype/freetype-2.4.2.tar.bz2',
		'build': """
			./configure --prefix=/tmp/install
			make
			make install
			""",
	},
	{
		'name': 'fontconfig',
		'source': 'http://www.fontconfig.org/release/fontconfig-2.8.0.tar.gz',
		'build': """
			./configure --prefix=/tmp/install --disable-docs
			make
			make install
			""",
	},
	{
		'name': 'cairo', 
		'source': 'http://cairographics.org/releases/cairo-1.8.10.tar.gz',
		'build': """
			./configure --prefix=/tmp/install --enable-quartz --enable-quartz-font --enable-quartz-image --enable-atsui --enable-pdf --disable-xlib --disable-ft
			make
			make install
			""",
	},
	#  TODO: There are problems relocating these binaries... is the max header flag not getting passed in?
	#  Hrm... the flag is getting set... which binary is failing?
	{
		'name': 'pango', 
		#'source': 'http://ftp.gnome.org/pub/GNOME/sources/pango/1.20/pango-1.20.2.tar.bz2',
		#'source': 'http://ftp.gnome.org/pub/GNOME/sources/pango/1.20/pango-1.20.5.tar.bz2',
		'source': 'http://ftp.gnome.org/pub/GNOME/sources/pango/1.28/pango-1.28.1.tar.bz2',
		'build': """

			find . -iname "makefile\.in" | xargs sed -i -e 's@which[[:space:]]*gtkdoc-rebase@/usr/bin/false@'
			# Hrm... LDFLAGS not getting set for atsui basic... for it (TODO: file bug)
			sed -e "s/framework Carbon/framework Carbon -headerpad_max_install_names/g" modules/basic/Makefile.in > new
			mv new modules/basic/Makefile.in

			# Patch to use atsui (for 1.26)
			#curl -L http://git.gnome.org/browse/pango/patch/?id=0f06d7758bc37a4942342d2c17a88944cbc88adb | patch -p1
			# Patch to fix ligature bug (1.26)
			#curl -L http://bugzilla-attachments.gnome.org/attachment.cgi?id=154892 | patch -p1

			# Hack the configure script to disable the FreeType backend
			#sed -i bak 's,2\.5\.0,9.5.0,' configure

			# Use this prefix so we don't have to do any tricks to relocate (Do this with all modules?)
			CFLAGS=" -DMAC_OS_X_VERSION_10_5=1050 $CFLAGS " ./configure --prefix=%s --without-x
			make

			rm -Rf /tmp/temp_install
			make install DESTDIR=/tmp/temp_install

			# Do this so all the zip files have the same base, and we can lay them back here later
			mkdir -p /tmp/install
			cd /tmp/temp_install%s || exit 1
			mv * /tmp/install
			""" % (prefix, prefix),
	},
	{
		'name': 'atk', 
		#'source': 'http://ftp.gnome.org/pub/gnome/sources/atk/1.20/atk-1.20.0.tar.bz2',
		#'source': 'http://ftp.gnome.org/pub/GNOME/sources/atk/1.23/atk-1.23.5.tar.bz2',
		'source': 'http://ftp.gnome.org/pub/GNOME/sources/atk/1.30/atk-1.30.0.tar.bz2',
		'build': """
			find . -iname "makefile\.in" | xargs sed -i -e 's@which[[:space:]]*gtkdoc-rebase@/usr/bin/false@'
			./configure --prefix=/tmp/install || exit 1
			make || exit 1
			make install || exit 1
		""",
	},
#	## Tarball generated on linux (opensuse 10.3) using:
#	# Applied patch: http://people.imendio.com/richard/patches/gtk-configure.patch
#	# Applied patch: from Geoff to remove some spew
#	./autogen.sh  --enable-gtk-doc
#	make
#	#  had to remove gtk/test from 'configure' script and from gtk/Makefile.am SUBDIRS ... why wasn't that in the tarball?
#	make dist-bzip2
	{
		# Requires 10.4 or above
		'name': 'gtk+', 
		'version': '2.20.1', 
		'source': 'http://ftp.gnome.org/pub/gnome/sources/gtk+/2.20/gtk+-2.20.1.tar.bz2',
		'build': """set -ex
			# The following is a hack for a gtk bug where 'which' does not act as expected on mac.
                        # see http://lists.macosforge.org/pipermail/macports-users/2007-December.txt and search for 'gtkdoc-rebase'
			find . -iname "makefile\.in" | xargs sed -i -e 's@which[[:space:]]*gtkdoc-rebase@/usr/bin/false@'
                        LDFLAGS="$LDFLAGS -framework Foundation -framework Carbon -framework AppKit -Xlinker -headerpad_max_install_names" ./configure --prefix=%s --with-gdktarget=quartz --disable-gtk-doc --with-libjpeg --without-libjasper
			make
			make install DESTDIR=/tmp/temp_install
			mkdir -p /tmp/temp_install/Library/Frameworks/Mono.framework/Versions/Current/share/themes/Mac/gtk-2.0-key
			curl -L http://mjhutchinson.com/files/temp/gtkrc-mac-2.20-hack > /tmp/temp_install/Library/Frameworks/Mono.framework/Versions/Current/share/themes/Mac/gtk-2.0-key/gtkrc

			# Do this so all the zip files have the same base, and we can lay them back here later
			mkdir -p /tmp/install
			cd /tmp/temp_install%s || exit 1
			mv * /tmp/install
			""" % (prefix, prefix),
	},
	{
		'name': 'libxml2',
		'source': 'http://ftp.gnome.org/pub/GNOME/sources/libxml2/2.6/libxml2-2.6.30.tar.bz2',
		'build': """
			./configure --prefix=/tmp/install --with-python=no
			make
			make install
		""",
	},
	{
		'name': 'librsvg', 
		'source': 'http://ftp.gnome.org/pub/GNOME/sources/librsvg/2.26/librsvg-2.26.3.tar.bz2',
	},
	{
		'name': 'libglade', 
		#'source': 'http://ftp.gnome.org/pub/GNOME/sources/libglade/2.6/libglade-2.6.2.tar.bz2',
		'source': 'http://ftp.gnome.org/pub/GNOME/sources/libglade/2.6/libglade-2.6.4.tar.bz2',
		'build':"""set -ex
			./configure --prefix=/tmp/install
			make
			make install
		"""
	},
        {
                'name': 'intltool',
                'source': 'http://ftp.gnome.org/pub/gnome/sources/intltool/0.40/intltool-0.40.6.tar.bz2',
                'build':"""
                        ./configure --prefix=/tmp/install
                        make
                        make install
                """

        },
	{
		'name': 'gtk-engines',
		'source': 'http://ftp.gnome.org/pub/GNOME/sources/gtk-engines/2.20/gtk-engines-2.20.1.tar.bz2',
		'pre':"""
                        # This is a total hack to fake out the check for xgettext.
                        # This can be removed once we get xgettext compiling on mac
                        echo -e '#!/bin/sh\necho "(GNU gettext"' > /tmp/build_deps/bin/xgettext
                        chmod 755 /tmp/build_deps/bin/xgettext
                """,
		'build':"""
                        ./configure --disable-nls --prefix=/tmp/install  
                        make
                        make install
                """,
	},
	{
		'name': 'murrine',
		'source': 'http://ftp.gnome.org/pub/GNOME/sources/murrine/0.90/murrine-0.90.3.tar.bz2',
	},
	{
		'name': 'gtk-quartz-engine',
		'source': 'http://build.mono.lab.novell.com/~builder/gtk-quartz-engine-0.2.tar.bz2',
		#'source': 'http://downloads.sourceforge.net/project/gtk-osx/GTK%20Quartz%20Engine/gtk-quartz-engine-0.2.tar.gz',
	},
	{
		'name': 'ige-mac-integration',
		'source': 'http://ftp.imendio.com/pub/imendio/ige-mac-integration/ige-mac-integration-0.8.2.tar.gz',
		#'source': 'http://downloads.sourceforge.net/project/gtk-osx/GTK-OSX%20Build/ige-mac-integration-0.9.4.tar.gz',
		'build':"""
			LDFLAGS="-framework AppKit -Xlinker -headerpad_max_install_names"  ./configure --prefix=/tmp/install
			make
			make install
		""",
	},
	{
		'name': 'sqlite',
		#'source': 'http://www.sqlite.org/sqlite-3.5.7.tar.gz',
		'source': 'http://www.sqlite.org/sqlite-3.6.23.1.tar.gz',
		'build':"""
			./configure --prefix=/tmp/install --disable-tcl
			make
			make install
		""",
		'post':"""
			rm -Rf /tmp/install/bin
			rm -Rf /tmp/install/man
			"""
	},



]

