#!/usr/bin/env python

# Hmm... pkgconfig fails when building with 10.3 sdk on 10.4... build the ppc deps on 10.3 for now.
# Ok, pkg is building, but now glib fails... fixed with LDFLAGS fixes in do-install-zip-pkgs
# Now build is failing on 10.4 with 10.3 sdk because we can't find /Developer/SDKs/MacOSX10.3.9.sdk glib stuff
#  Ugh.. had to do a symlink from /Developer/SDKs/MacOSX10.3.9.sdk/tmp to /tmp as a workaround

BUILD_HOSTS = ['macos-10-ppc', 'macos-10-x86']

packages = [
	{
		'name': 'pkg-config', 
		'source': 'http://pkgconfig.freedesktop.org/releases/pkg-config-0.22.tar.gz',
		'post':"""
			# Configure shell wrapper for pkg-config so it will look for .pc files when installed (#79671)
			cd /tmp/install/bin
			mv pkg-config pkg-config.bin
			cat <<EOF > pkg-config
#!/bin/sh
PKG_CONFIG_PATH=/tmp/install/lib/pkgconfig:\$PKG_CONFIG_PATH /tmp/install/bin/pkg-config.bin "\$@"
EOF
			chmod 755 pkg-config
			"""
	},
	{
		'name': 'gettext', 
		'source': 'http://ftp.gnu.org/pub/gnu/gettext/gettext-0.16.1.tar.gz',
		'post':"""
			# Save msgfmt, as this is needed for building glib
			rm -Rf /tmp/temp_install
			mkdir -p /tmp/temp_install/bin
			mv /tmp/install/bin/msgfmt /tmp/temp_install/bin

			rm -Rf /tmp/install/bin/*
			rm -Rf /tmp/install/share/doc
			rm -Rf /tmp/install/share/emacs
			rm -Rf /tmp/install/share/gettext

			mv /tmp/temp_install/bin/msgfmt /tmp/install/bin
			"""
	},
	{
		'name': 'glib', 
		'source': 'ftp://ftp.gtk.org/pub/glib/2.14/glib-2.14.1.tar.bz2',
		'post':"""
			rm -Rf /tmp/install/bin/*
			rm -Rf /tmp/install/share/gtk-doc
			"""
	},
	{
		'name': 'jpeg', 
		'version': '6b',
		'source': 'ftp://ftp.uu.net/graphics/jpeg/jpegsrc.v6b.tar.gz',
		'build':
			"""ln -s `which glibtool` ./libtool

			./configure --enable-shared --enable-static --enable-freetype --prefix=/tmp/install
			make || exit 1
			mkdir -p /tmp/install/lib
			mkdir -p /tmp/install/include
			make install-lib || exit 1
			"""
	},
	{
		'name': 'tiff', 
		'source': 'ftp://ftp.remotesensing.org/pub/libtiff/tiff-3.8.2.tar.gz',
		'build':
			"""
			./configure --prefix=/tmp/install --mandir=/tmp/install/share/man \
				--with-jpeg-include-dir=/tmp/build_deps/include --with-jpeg-lib-dir=/tmp/build_deps/lib

			# 3.8.2's libtool didn't like the sysroot for building on 10.3
			rm libtool
			ln -s `which glibtool` ./libtool

			make || exit 1
			cd libtiff
			make install || exit 1
			"""
	},
	{
		'name': 'libpng',
		'source': 'http://superb-east.dl.sourceforge.net/sourceforge/libpng/libpng-1.2.20.tar.bz2',
		'post':"""
			rm -Rf /tmp/install/bin/*
			# How did this get installed?? (we want .dylib, not .so)
			rm -Rf /tmp/install/lib/libpng.so
			"""
	},
	{
		'name': 'giflib', 
		'source': 'http://easynews.dl.sourceforge.net/sourceforge/giflib/giflib-4.1.6.tar.bz2',
		'post':"""
			rm -Rf /tmp/install/bin/*
			"""
	},
	# Include this because macosx freetype is too old for the new cairo
	# (Tiger's used to be sufficient, but it looks like the new cairo needs newer than Tiger's)
	{
		'name': 'freetype', 
		'source': 'http://download.savannah.gnu.org/releases/freetype/freetype-2.1.10.tar.bz2',
		'post':"""
			rm -Rf /tmp/install/bin/*
			"""
	},
	# Include our own because 10.3 and 10.4 ppc have differing expat versions
	{
		'name': 'expat', 
		'source': 'http://easynews.dl.sourceforge.net/sourceforge/expat/expat-2.0.1.tar.gz',
		'post':"""
			rm -Rf /tmp/install/bin
			rm -Rf /tmp/install/man
			"""
	},
]


