@ECHO OFF
SETLOCAL
SET PATH=@@DOS_MONO_INST_DIR@@\bin;%PATH%
SET MONO_PATH=@@DOS_MONO_INST_DIR@@\lib
SET MONO_CFG_DIR=@@DOS_MONO_INST_DIR@@\etc
"@@DOS_MONO_INST_DIR@@\bin\mono.exe" "@@DOS_MONO_INST_DIR@@\lib\mono\1.0\@@MONO_WRAPPER@@.exe" %*
ENDLOCAL
