#!/bin/sh

CHECKDIR=/tmp/co
PREFIX=/tmp/prefix
VERSION=0.31

rm -rf $CHECKDIR $PREFIX

mkdir $CHECKDIR
cd $CHECKDIR
echo > log
cvs co mcs mono 2>&1 >> log
cp -a mcs mcs-$VERSION

#
# Build MCS
#
echo Building MCS
(cd $CHECKDIR/mcs; ./configure --profile=default --prefix=$PREFIX; make || exit 1) 2>&1 >> log

#
# Build Mono
#
echo Building Mono
(cd $CHECKDIR/mono; ./autogen.sh --prefix=$PREFIX; make && make install) 2>&1 >> log

echo Running make distcheck
(cd $CHECKDIR/mono && make distcheck) 2>&1 >> log

echo Packaging MCS
tar czf mcs-$VERSION.tar.gz mcs-$VERSION 2>&1 >> log

cp mcs-$VERSION.tar.gz /tmp/
cp mono/mono-$VERSION.tar.gz /tmp

echo -------------------------------
echo - The files:
echo -------------------------------

ls -l /*$VERSION.tar.gz

