#!/bin/sh
#
# Usage: build [os-target] [package] [version]
#
# Where:
#    os-target is the OS target that we are building for
#    package is the name of the BB XML configuration file on the repository
#    version is the version you want to build
#
# Example:
#    build suse-92-i386 mono-1.1 1.1.6
#

distro=$1
package=$2
version=$3

. shared-code.sh

LOGFILE=logs/$package-$version-$distro
rm -rf $LOGFILE

mkdir -p `dirname $LOGFILE`

usage()
{
	echo "Usage is: build configuration package version"
}

if test x$version = x; then
    usage
    exit 1;
fi

if test -f status/$distro; then
   echo There is already a build in progress on $1
   exit 1
fi

. conf/$distro
. defs/$package


if [ ! ${#MONO_DEPS[@]} -eq 0 ]; then
	if ! ./install-deps $distro ${MONO_DEPS[@]} >> $LOGFILE 2>&1; then
		echo Dependency installation failed, see log in $LOGFILE for details
		exit 1
	fi
fi

scp do-build ../conf/$package/ximian-build.conf sources/$package/*-$version.tar.gz $target_host:$jaildir/tmp 

echo > status/$distro;
if ! ./jail-do $distro sh -x /tmp/do-build $version >> $LOGFILE 2>&1; then
	rm status/$distro
	echo Build failed, see log in $LOGFILE for details
	exit 1;
fi

rm status/$distro

distro_info $distro
get_destroot $distro

mkdir -p packages/$DEST_ROOT/$package
scp $target_host:$jaildir/tmp/root/built-packages/* packages/$DEST_ROOT/$package

one_rpm=`ls -1 packages/$DEST_ROOT/$package/*.rpm | head -n1`
ver=`rpm_query VERSION $one_rpm`
mkdir -p packages/$DEST_ROOT/$package/$ver
mv packages/$DEST_ROOT/$package/*.rpm packages/$DEST_ROOT/$package/$ver