#!/usr/bin/env python

import sys

import pdb

sys.path+=['../pyutils']

import packaging

if len(sys.argv) < 4:
        print "Usage: dep_builder <jail> <dep_def filename> <release>"
        sys.exit(1)

jail = sys.argv[1]
def_filename = sys.argv[2]
release = sys.argv[3]

conf = packaging.buildconf(jail)

build_location = conf.env_vars['build_location']

#pdb.set_trace()

conf.buildenv.copy_to(['do-dep-build', 'dep_defs/' + def_filename, '../pyutils/*.py', 'do-install-zip-pkgs', '../pyutils/rpm2cpio.py', 'conf/' + jail], build_location)

code, output = conf.buildenv.execute_command('%s/do-dep-build %s %s %s' % (build_location, jail, def_filename, release) )

if code:
	print "Error building deps..."
	conf.buildenv.unlock_env()
	sys.exit(1)

# Copy files back
conf.buildenv.copy_from(build_location + '/build/built-packages/*', 'external_zip_pkg')

conf.buildenv.unlock_env()
