#!/bin/sh

# Run the builds as the builder user inside the jail
SUDO='sudo -H -u builder'

mount /proc &> /dev/null

version=$1
rev=$2
rm -rf /tmp/builder/built-packages 	|| exit 1
cd /tmp && rm -rf scratch 		|| exit 1
$SUDO mkdir scratch && cd scratch 	|| exit 1

mv ../ximian-build.conf .
mv ../*.patch .
mv ../*.tar.gz .
# rpm needs this to be happy
chown root:root *.tar.gz
chown root:root *.patch


$SUDO bb_lint -g prebuild -V $version -R $rev -S ''	|| exit 1
$SUDO bb_unpack apply					|| exit 1

# remove some stuff in order to conserve space... (some boxes don't have much to spare)
rm -rf /tmp/builder/built-packages/*.src.rpm

$SUDO bb_do -V $version -R $rev -S ''			|| exit 1
$SUDO bb_lint -V $version -R $rev -S ''			|| exit 1


