#!/bin/sh

# Run the builds as the builder user inside the jail  ...
if [ `id -u` == "0" ] ; then
	SUDO_USER='sudo -H -u builder'
	SUDO_ROOT=''
else
	SUDO_USER=''
	SUDO_ROOT='sudo'
fi

$SUDO_ROOT mount /proc &> /dev/null

version=$1
rev=$2
$SUDO_ROOT rm -rf /tmp/builder/built-packages 	|| exit 1
$SUDO_ROOT cd /tmp && rm -rf scratch 		|| exit 1
$SUDO_USER mkdir scratch && cd scratch 		|| exit 1

mv ../ximian-build.conf .
mv ../*.patch .
mv ../*.tar.gz .
mv ../*.zip .
# rpm needs this to be happy
$SUDO_ROOT chown root:root *.tar.gz
$SUDO_ROOT chown root:root *.zip
$SUDO_ROOT chown root:root *.patch

$SUDO_USER bb_lint -g prebuild -V $version -R $rev -S ''	|| exit 1
$SUDO_USER bb_unpack apply					|| exit 1
$SUDO_USER bb_do -V $version -R $rev -S ''			|| exit 1
$SUDO_USER bb_lint -V $version -R $rev -S ''			|| exit 1

$SUDO_USER rm -rf /tmp/builder/built-packages/*.src.rpm

