#!/bin/sh

# Some things we'll need to run as root
EXEC_AS_ROOT='sudo'

$EXEC_AS_ROOT mount /proc &> /dev/null

version=$1
rev=$2
build_location=$3
rm -rf $build_location/builder/built-packages 		|| exit 1
# Make sure it exists...
mkdir -p $build_location				|| exit 1
cd $build_location && rm -rf scratch		 	|| exit 1
mkdir scratch && cd scratch 				|| exit 1

# These need sudo because the uids of builder of the host and jail may not match up
$EXEC_AS_ROOT mv ../ximian-build.conf .
$EXEC_AS_ROOT mv ../*.patch .
$EXEC_AS_ROOT mv ../*.tar.gz .
$EXEC_AS_ROOT mv ../*.zip .

# rpm needs this to be happy
$EXEC_AS_ROOT chown root:root *.tar.gz
$EXEC_AS_ROOT chown root:root *.zip
$EXEC_AS_ROOT chown root:root *.patch

archive_dir="$build_location/builder/built-packages"

bb_lint -g prebuild -V $version -R $rev -S ''		|| exit 1
bb_unpack apply						|| exit 1
bb_do -V $version -R $rev -S '' -a $archive_dir 	|| exit 1
bb_lint -V $version -R $rev -S ''			|| exit 1

rm -rf $archive_dir/*.src.rpm

