#!/bin/sh

PACKAGES="$*"

if [ ! -f /usr/sbin/rcd ]; then
	echo "No red carpet!!"
	exit 1;
fi

/etc/init.d/rcd start 
rug ping

while ! rug ping; do echo waiting; done

rug solvedeps -yr $PACKAGES || exit 1

/etc/init.d/rcd stop &> /dev/null

exit 0