#!/usr/bin/env python
#
# The driver script to make a tarball
#

import sys
import os
import tempfile
import shutil
import glob
import distutils.dir_util

import packaging

HEAD_or_RELEASE = sys.argv[1]
package = sys.argv[2]
version = sys.argv[3]

os.chdir('/tmp')

dummy_env = ""
package_obj = packaging.package(dummy_env, package, inside_jail=True)

if os.path.exists('tarball-creation'):
	shutil.rmtree('tarball-creation')
os.mkdir('tarball-creation')
os.chdir('tarball-creation')


# Construct subversion path of location we want to create a tarball from
svn_paths = []
if HEAD_or_RELEASE == "HEAD":
	rev_arg = "-r " + version
	if package_obj.info.has_key('HEAD_PATH'):
		svn_paths += package_obj.info['HEAD_PATH']

else:
	rev_arg = ""
	if package_obj.info.has_key('RELEASE_PATH'):
		svn_paths += package_obj.info['RELEASE_PATH']

	# Do some svn_path munging
	# (options: [[version]], [[versiondot]], [[gtksharp2ver]]
	version_dot = version
	version_hyphen = version.replace('.', '-')

	for i in range(0, len(svn_paths)):
		svn_paths[i] = svn_paths[i].replace('[[versiondot]]', version_dot)
		svn_paths[i] = svn_paths[i].replace('[[version]]', version_hyphen)


# use the key in /usr/share/ximian-build-system/conf/ssh
# This needs to be exported to the environment
SVN_SSH = "/usr/bin/bb_ssh"
SVNEXPORT = "svn export -q " + rev_arg
MONO_ROOT = " svn+ssh://distro@mono-cvs.ximian.com/source" 
SVN_PATHS = ":".join(svn_paths)
VERSION = version

# print env
print "SVN_SSH: %s" % SVN_SSH
print "SVNEXPORT: %s" % SVNEXPORT
print "MONO_ROOT: %s" % MONO_ROOT
print "HEAD_or_RELEASE: %s" % HEAD_or_RELEASE
print "SVN_PATHS: %s" % SVN_PATHS
print "VERSION: %s" % VERSION

# set env
os.environ['SVN_SSH'] = SVN_SSH
os.environ['SVNEXPORT'] = SVNEXPORT
os.environ['MONO_ROOT'] = MONO_ROOT
os.environ['HEAD_or_RELEASE'] = HEAD_or_RELEASE
os.environ['SVN_PATHS'] = SVN_PATHS
os.environ['VERSION'] = VERSION

# If they don't have any svn_paths, they MUST specify BUILD_DIR
if package_obj.info.has_key('BUILD_DIR'):
	build_dir = package_obj.info['BUILD_DIR']
else:
	try:
		build_dir = os.path.basename(svn_paths[0])
	except:
		print "You must specify BUILD_DIR in def file when not using RELEASE or HEAD PATH"
		sys.exit(1)

# Maybe we'll eventually use python code in the def file someday...
update_version_file = package_obj.get_info_var('update_version_file')
if not update_version_file:
	update_version_file = """
	sed -i "s/\(AM_INIT_AUTOMAKE.*,\\).*)/\\1$VERSION)/" configure.in
"""

make_dist = package_obj.get_info_var('make_dist')
if not make_dist:
	make_dist = """
	# profile is needed on suse systems with gnome in /opt
	. /etc/profile
        ./autogen.sh
        make dist-bzip2
"""

get_source = package_obj.get_info_var('get_source')

# pwd: /tmp/tarball-creation

### Execute the source creating functions ###
def_file = "/tmp/" + package

# Clean up bb_ssh dirs, otherwise, collisions happen, causing svn commands to fail
os.system("rm -Rf /tmp/bb_ssh*")

# get_source
if get_source:
	print "Command: %s" % get_source
	os.system(get_source)
else:
	cache_dir = "/tmp/src_cache/%s/%s" % (package, HEAD_or_RELEASE)
	for path in svn_paths:
		module = os.path.basename(path)

		# Do we have a working copy already?
		if os.path.exists("%s/%s" % (cache_dir, module)):
			# svn switch  (will update update if the path in the working copy hasn't changed, this ensures have the right path)
			command = 'cd %s/%s; svn switch %s %s/%s' % (cache_dir, module, rev_arg, MONO_ROOT, path)
			print "Executing: " + command
			if os.system(command):
				print "*** Error *** updating cached copy failed (this is usually because of a malformed url, ex: invalid version, or bb_ssh failed)"
				sys.exit(1)
		else:
			# create cache dir
			if not os.path.exists(cache_dir): distutils.dir_util.mkpath(cache_dir)
			#check out working copy
			command = "cd %s; svn checkout -q %s %s/%s" % (cache_dir, rev_arg, MONO_ROOT, path)
			print command
			os.system(command)


		# svn export from working copy
		#command = "%s %s/%s" % (SVNEXPORT, MONO_ROOT, path)
		#command = "%s %s/%s" % (SVNEXPORT, cache_dir, module)
		# Note: using -r rev with svn export from a local cache dir will connect to the svn server... bad

		#command = "svn export -q %s/%s" % (cache_dir, module)
		#  svn export from a working dir pegs the processor at 99%!!  also bad... it also takes longer (3 minutes... ?)

		#  Use rsync instead?  probably...
		# results: using this instead of svn export recovers those 3 minutes
		command = "rsync -a --exclude '.svn/' %s/%s ." % (cache_dir, module)

		print command
		os.system(command)


# Go inside the source tree
os.chdir(build_dir)

# update_version_file (If this is a snapshot build)
if HEAD_or_RELEASE == "HEAD":
	os.system(update_version_file )

# pwd: /tmp/tarball-creation/$build_dir

# make_dist
os.system(make_dist)

### End of source creating functions ###

### Finish moving things around
if os.path.exists('/tmp/built-tarball'):
	shutil.rmtree('/tmp/built-tarball')
os.mkdir('/tmp/built-tarball')

found_source_file = 0
source_files = glob.glob('*.zip') + glob.glob('*.tar.gz') + glob.glob('*.tar.bz2')

if len(source_files) == 1:
	os.rename(source_files[0], '/tmp/built-tarball/%s' % source_files[0])
	found_source_file = 1
	print "print source filename..."
	print source_files[0]

# Clean up
os.chdir('/tmp')
shutil.rmtree('tarball-creation')

# Propogate exit code
if not found_source_file:
	sys.exit(1)

