#!/usr/bin/env python

import sys

sys.path += ['../pyutils']

import src_repo_utils
import packaging
import config
import utils


if len(sys.argv) < 4:
	print "Usage: ./get-range-revs <package> <start rev> <end rev>"
	sys.exit(1)

package_name = sys.argv[1]
start = sys.argv[2]
end = sys.argv[3]

repo = src_repo_utils.svn(config.MONO_ROOT)

pack = packaging.package("", package_name)

revs = []
for i in range(int(start), int(end)):
	revs.append(repo.latest_path_revision(pack.info['HEAD_PATH'], revision=i))

revs = utils.remove_list_duplicates(revs)

print revs

