#!/usr/bin/env python

import sys

sys.path += ['../pyutils']

import src_repo_utils
import packaging
import config
import utils


if len(sys.argv) < 4:
	print "Usage: ./get-range-revs <package> <start rev> <end rev>"
	sys.exit(1)

package_name = sys.argv[1]
start = sys.argv[2]
end = sys.argv[3]

repo = src_repo_utils.svn(config.MONO_ROOT, key_file=config.src_key_file)

pack = packaging.package("", package_name)

revs = []
# add 1 to end because range() doesn't include it
revs_to_try = range(int(start), int(end) + 1)
revs_to_try.reverse()
latest_rev = int(end)

for i in revs_to_try:
	# If we're trying something in the list we know doesn't exist, skip to the next try
	if i > latest_rev:
		continue

	latest_rev = repo.latest_path_revision(pack.info['HEAD_PATH'], revision=i)
	revs.append(latest_rev)

revs = utils.remove_list_duplicates(revs)
revs.reverse()

print revs

