#!/bin/sh

package=$1

if [ -z $package ] ; then
	echo "Usage: ./get-latest-rev <package>"
	exit 1
fi

. defs/$package

if [ "$package" == "monodevelop" ]; then
	ROOT=svn+ssh://mono-cvs.ximian.com/svn/monodevelop
else
	ROOT=svn+ssh://mono-cvs.ximian.com/source
fi

svn ls $ROOT/$HEAD_PATH -v | awk '{print $1}' | sort -nr | head -n1 

