#!/usr/bin/env python

import sys

sys.path += ['../pyutils']

import src_repo_utils
import packaging
import config


if len(sys.argv) < 2:
	print "Usage: ./get-latest-rev <package>"
	sys.exit(1)

package_name = sys.argv[1]

repo = src_repo_utils.svn(config.MONO_ROOT, key_file=config.src_key_file)

pack = packaging.package("", package_name)

print repo.latest_path_revision(pack.info['HEAD_PATH'])


