#!/bin/sh
#
# Usage: install-deps TARGET monopackages
#    ex: install-deps suse-93-i586 mono-1.1 gtk-sharp-2.0
#

. shared-code.sh

TARGET=$1
shift
DEPS=$*

. conf/$TARGET
distro_info $TARGET

RPMS=()

for i in $DEPS; do
	. defs/$i
	
	get_destroot
	
	if ! latest_version packages/$DEST_ROOT/$i; then
		echo "Could not find $i for $DISTRO (looking in $DEST_ROOT)"
		exit 1;
	fi
	
	for i in $LATEST_VERSION/*.rpm; do
		[[ $i == *.src.rpm ]] && continue
		
		RPMS=(${RPMS[@]} $i)
	done
done

[ ${#RPMS[@]} -eq 0 ] && exit 0

rpm_names=$(rpm -qp --queryformat '%{NAME} ' ${RPMS[@]})

./jail-do $TARGET "sh -x -c \"rm -rf /tmp/install-packages; mkdir -p /tmp/install-packages -m777\""

scp ${RPMS[@]} $target_host:$jaildir/tmp/install-packages

./jail-do $TARGET "sh -x -c \"/etc/init.d/rcd restart\""
./jail-do $TARGET "sh -x -c \"rug rm -y $rpm_names\""
./jail-do $TARGET "sh -x -c \"rug in -y -r /tmp/install-packages/*.rpm\""
#./jail-do $TARGET "sh -x -c \"/etc/init.d/rcd stop\""
#./jail-do $TARGET "sh -x -c \"rm -rf /tmp/install-packages\""


