#!/usr/bin/env python

import sys
import string

sys.path += ['../pyutils']

import buildenv
import packaging

if len(sys.argv) < 2:
	print "Usage: ./jail-do <distro conf> [command]"
	print "  Example: ./jail-do suse-93-i586 ls"
	print "  If no [command] is given, an interactive login will proceed"
	sys.exit(1)

conf = packaging.buildconf(sys.argv[1], skip_alternates=True)
conf.buildenv.print_output=True

if len(sys.argv) > 2:
	command = string.join(sys.argv[2:], ' ')
	sys.stderr.write("Executing: %s\n" % command)
	status, output = conf.buildenv.execute_command(command)
	sys.exit(status)
else:
	print "Logging in"
	conf.buildenv.login()

