#!/bin/sh
#
# Executes either a command or an interactive shell on a jail
# ./jail-do suse-93-i586
# ./jail-do suse-93-i586 rug in my-package
#

TARGET=$1
shift

. conf/$TARGET
. shared-code.sh

#
# FIXME
#
# There are weird things happening with quoting here. You can't
# pass a command with single quotes. We need to fix this somewhow
#

SSH_FLAGS="-q"

if [ "x$*" == x ] ; then
	CMD="bash -l"
	# allocate a tty
	SSH_FLAGS="$SSH_FLAGS -t"
else
	CMD="bash -lc '$*'"
fi

#
# redhat systems have chroot in sbin, so we need to add that to
# the path while we ssh in.
#
ADD_SBIN='PATH=/sbin:/usr/sbin:$PATH'

ssh $SSH_FLAGS $target_host "$ADD_SBIN sudo -H chroot $jaildir $CMD"
