#!/usr/bin/env python

import os
import sys
import commands

sys.path.append("../pyutils")
import config

try:
	(junk, branch_version, tag_version) = sys.argv
except:
	print "Usage: ./branch_diff <mono branch version> <mono tag version>"
	print "  diff all modules in the tag against those in the branch."
	print "  Places diffs in ./diffs ."
	sys.exit(1)

branch_version = branch_version.replace(".", "-")
tag_version = tag_version.replace(".", "-")

ssh_env = 'SVN_SSH="ssh %s"' % config.ssh_options
status, output = commands.getstatusoutput("%s svn ls %s/tags/mono-%s" % (ssh_env, config.MONO_ROOT, tag_version))

if not os.path.exists('diffs'): os.mkdir('diffs')

updated_modules = []

for module in output.split("\n"):
	#  Call dirname to strip off ending '/'
	module = os.path.dirname(module)
	print "Checking for changes in: " + module
	status, output = commands.getstatusoutput("%s svn diff %s/tags/mono-%s/%s %s/branches/mono-%s/%s" % (ssh_env, config.MONO_ROOT, tag_version, module, config.MONO_ROOT, branch_version, module))

	if output:
		print "Changes found for: " + module
		fd = open('diffs/' + module, "w")
		fd.write(output)
		fd.close()
		updated_modules.append(module)

print "Updated modules: " + " ".join(updated_modules)
