#!/bin/sh

version=$1
shift

rm -f bscripts/*
for product in $*; do
	. defs/$product 
	
	for target_distro in ${BUILD_HOSTS[@]}; do
		. conf/$target_distro
		
		echo sh build $target_distro $product $version >> bscripts/$target_host
		if echo $hosts | grep -qv $target_host;  then
			hosts="$hosts $target_host";
		fi
	done
done

count=0
for i in `echo $hosts`; do
	mv bscripts/$i bscripts/$count
	count=$[$count+1]
done
