#!/usr/bin/env python

# Script to remove rpms and their depedents (sometimes easier to use this script rather that get rug/rcd working on a particular distro)

# Usage: ./remove-rpms rpm1 rpm2 rpm3

import sys
import os

sys.path.append("../pyutils")

import rpm_utils

# Make sure we are root
if not os.getuid() == 0:
	print "Must be super user to run this script..."
	sys.exit(1)

if len(sys.argv) < 2:
	print "Usage: ./remove-rpms rpm1 rpm2 ..."
	sys.exit(1)

rpms = sys.argv[1:]

removed_rpms = rpm_utils.remove_rpms(rpms)

print "\nRemoved the following rpms:\n\n" + "\n".join(removed_rpms)
print "\n -- RPM removal Complete! -- \n"


