#!/bin/sh

BUNDLE="trunk"
STAGE_DIR="$(pwd)/stage/snapshot"

TARGET_USER="mono-web"
TARGET_HOST="mono.ximian.com"
TARGET_DIR="~/release/monobuild/www"
TARGET_URL="/monobuild/snapshot"

# Hack: flag to mono-basic to grab from noarch instead of $DISTRO
export UPLOAD_SNAPSHOT=1

distros="suse-101-i586,suse-103-i586,suse-103-x86_64"

mkdir -p $STAGE_DIR
cd ../website
cp packaging.css $STAGE_DIR

# run a script that cleans up all but one version... 
./clean-downloads.py --source_basepath=$STAGE_DIR/snapshot_sources --package_basepath=$STAGE_DIR/snapshot_packages --platforms=$distros HEAD 1

./sync-bundle.py  --platforms=$distros --skip_installers $BUNDLE $STAGE_DIR || exit 1

# Copy non snapshot packages and sources (external stuff) to the snapshot_ dirs
#  This shouldn't have much of an impact on rsync since we'll leave the originals in place
#  also clean up generated stuff
cd $STAGE_DIR
cp -a sources/* snapshot_sources
cp -a packages/* snapshot_packages
rm -Rf download-trunk sources-trunk archive/trunk
cd -

# problem: it's possible a tarball will be built, but we won't have any packages... issue?
#   possible long solution: generate bundles/trunk to have all the right info... ugh

./mk-sources-index.py           				$BUNDLE $STAGE_DIR $TARGET_URL $STAGE_DIR/snapshot_sources			|| exit 1
./mk-distro-index.py	--platforms=$distros --skip_zip		$BUNDLE $STAGE_DIR $TARGET_URL $STAGE_DIR/snapshot_packages $TARGET_HOST	|| exit 1
./mk-archive-index.py	--platforms=$distros --skip_installers	$BUNDLE $STAGE_DIR $TARGET_URL							|| exit 1
./mk-repos.py		--platforms=$distros			$BUNDLE $STAGE_DIR $TARGET_URL $STAGE_DIR/snapshot_packages $TARGET_HOST	|| exit 1

# Publish stage
ssh $TARGET_USER@$TARGET_HOST "mkdir -p $TARGET_DIR"
rsync -avzH --delete $STAGE_DIR $TARGET_USER@$TARGET_HOST:$TARGET_DIR
