#!/bin/sh

if [[ x$DISTRO == xfedora-* ]]; then
	RC_URL="http://www.snorp.net/files/packages/rcd-fc3/"
else
	RC_URL="ftp://ftp.ximian.com/pub/redcarpet2/$DISTRO"
fi

case $DISTRO in
	suse-100-*)
		DOWNLOAD_RC="To get Red Carpet, go to <a href='http://primates.ximian.com/~rml/sanitize/'>here</a>."
	;;
	suse-93-*)
		DOWNLOAD_RC="To get Red Carpet, install the rcd and rug packages via YAST"
	;;
	rhel-*)
		DOWNLOAD_RC=""
	;;
	* )
		DOWNLOAD_RC="If you do not already have Red Carpet, you can <a href='$RC_URL'>download it.</a>"
	;;
esac

cat <<EOF
	<p>
	The best way to install Mono on your system is to use Novell's Red Carpet.
	$DOWNLOAD_RC
	</p>
	
	<p>To use Red Carpet, execute these commands:</p>
	
	<xmp class='shell'>
rug sa http://go-mono.com/download
rug sub mono-1.1-official
rug sub gtk-sharp-official
rug sub mono-tools-official
rug in mono-complete gtk-sharp
	</xmp>

	<p>Note: some versions of Red Carpet frequently have IOError timeouts.  This is a bug in Red Carpet.  If Red Carpet for your distro frequently has this problem, please use another installation method.</p>
<p>

EOF

case $DISTRO in
    fedora-*)
	cat <<EOF
<p>
Another way to install updates on your operating system is to use <tt>yum</tt>. Putting the
<a href="mono.repo">mono.repo</a> file in <tt>/etc/yum.repos.d</tt> will allow you to
install mono and related packages.
</p>
EOF

	cat > $DISTRO/mono.repo <<"EOF"
[mono-1.1]
name=Mono 1.1 for fedora-$releasever-$basearch
baseurl=http://go-mono.com/download/mono-1.1/fedora-$releasever-$basearch/
enabled=1
gpgcheck=0

[gtk-sharp-1.0]
name=Gtk# 1.0 for fedora-$releasever-$basearch
baseurl=http://go-mono.com/download/gtk-sharp/fedora-$releasever-$basearch/
enabled=1
gpgcheck=0

[gtk-sharp-2.0]
name=Gtk# 2.0 for fedora-$releasever-$basearch
baseurl=http://go-mono.com/download/gtk-sharp-2.0/fedora-$releasever-$basearch/
enabled=1
gpgcheck=0

[mono-tools]
name=Mono Tools for fedora-$releasever-$basearch
baseurl=http://go-mono.com/download/mono-tools/fedora-$releasever-$basearch/
enabled=1
gpgcheck=0

[mono-deps]
name=Mono Deps for fedora-$releasever-$basearch
baseurl=http://go-mono.com/download/mono-deps/fedora-$releasever-$basearch/
enabled=1
gpgcheck=0
EOF
    ;;
esac
