#!/bin/bash -e
BASEURL="http://build.mono.lab.novell.com/builds/HEAD"
NAME="novell-moonlight"
DEST="mono-web@go-mono.com:/var/www/mono-website/go-mono/archive/moonlight-plugins"
TMPDIR=${TMPDIR:-/tmp}

if [ -z "$1" ]; then
	echo "Please supply a revision"
	exit 1
else
	REVISION="$1"
fi

rm -f $TMPDIR/novell-moonlight-*-*.xpi
for version in "1.0" "1.1"; do
	for arch in "i586" "x86_64"; do
		for media in "" "-ffmpeg"; do
			DISTRO="suse-101-$arch"
			echo "Fetching $NAME$media-$version-$arch.xpi"
			curl --fail -o "$TMPDIR/$NAME$media-$version-$arch.xpi" "$BASEURL/$DISTRO/moon/$REVISION/files/steps/plugin-$version$media/novell-moonlight.xpi"
		done
	done
done

echo "Uploading files"
rsync --verbose --progress $TMPDIR/novell-moonlight-*-*.xpi $DEST/

rm -f $TMPDIR/novell-moonlight-*-*.xpi
