#!/bin/bash -e
BASEURL="http://build.mono.lab.novell.com/builds/HEAD"
NAME="novell-moonlight"
DEST="go-mono.com:/var/www/mono-website/go-mono/archive/moonlight-plugins"

if [ -z "$1" ]; then
	echo "Please supply a revision"
	exit 1
else
	REVISION="$1"
fi

rm -f $TMPDIR/novell-moonlight-*-*.xpi
for version in "1.0" "1.1"; do
	for arch in "i586" "x86_64"; do
		basearch="$arch"
		[ "$arch" == "i586" ] && basearch="i386"
		DISTRO="suse-101-$arch"
		echo "Fetching $NAME-$version-$basearch.xpi"
		curl -o "$TMPDIR/$NAME-$version-$basearch.xpi" "$BASEURL/$DISTRO/moon/$REVISION/files/steps/plugin-$version/novell-moonlight.xpi"
	done
done

echo "Uploading files"
rsync --verbose --progress $TMPDIR/novell-moonlight-*-*.xpi $DEST/

rm -f $TMPDIR/novell-moonlight-*-*.xpi
