#!/bin/sh -x

#Create the links in the framework to have it fit the normal Framework structure.
if [ -d /Library/Frameworks/Mono.framework ]; then
    cd /Library/Frameworks/Mono.framework
    ln -sf Versions/Current/lib Libraries
    ln -sf Versions/Current/include Headers
    ln -sf Versions/Current/bin Commands
else 
    echo "/Library/Frameworks/Mono.framework does not exist"
fi

if [ -d /Library/Frameworks/Mono.framework/Commands ]; then
cd /Library/Frameworks/Mono.framework/Commands
for i in `ls -al | grep -v .exe | awk '{print $9}'`; do 
    echo ${i}
    ln -sf $PWD/${i} /usr/bin/${i}
done;
else 
    echo "/Library/Frameworks/Mono.framework/Commands does not exist"
fi

if [ -e /Library/Frameworks/Mono.framework/Libraries/libmono.dylib ];then
    ln -sf /Library/Frameworks/Mono.framework/Libraries/libmono.dylib /Library/Frameworks/Mono.framework/Mono
else
    echo "/Library/Frameworks/Mono.framework/Libraries/libmono.dylib does not exist"
fi
