#!/bin/bash

MONO_PREFIX=/opt/mono
GNOME_PREFIX=/opt/gnome
PATH=$MONO_PREFIX/bin:$PATH
PS1="mono@\h> "

export LD_LIBRARY_PATH=$MONO_PREFIX/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$MONO_PREFIX/include:$GNOME_PREFIX/include
export ACLOCAL_PATH=$MONO_PREFIX/share/aclocal
export PKG_CONFIG_PATH=$MONO_PREFIX/lib/pkgconfig:$GNOME_PREFIX/lib/pkgconfig
export CONFIG_SITE="$HOME/.config/automake/config.site"

