#!/usr/bin/env python

"""
TODO:
-Should I delete some of the extra junk that my dep packages install?
-Fix the csh script (vars failing that weren't previously set)

x Build/package libgdiplus
x probably should use ./jail-do just in case we end up doing this in a jail (done with packaging.py)
x Release (ChangLog)
x packages_used.txt
"""

"""
libgdiplus notes:
x freetype will be needed (probably also fontconfig)
x also, add image types to build deps: png gif tiff jpeg

"""

import commands
import os
import os.path
import sys
import shutil
import pdb
import glob
import re
import distutils.dir_util
import threading

sys.path += ['../pyutils']
import utils
import packaging
import config

# Constants
# Which noarch packages to include in the various packages
rpm_packages_to_include = {}
zip_packages_to_include = {}

zip_packages_to_include['sunos-8-sparc'] = ['mono', 'libgdiplus' ]
rpm_packages_to_include['sunos-8-sparc'] = ['xsp', 'ikvm', 'boo', 'monodoc' ]

zip_packages_to_include['sunos-10-sparc'] = ['mono', 'libgdiplus', 'gtk-sharp-2.0', 'gtk-sharp' ]
rpm_packages_to_include['sunos-10-sparc'] = ['xsp', 'ikvm', 'boo', 'monodoc', 'mono-tools', 'monodevelop', 'gtksourceview-sharp-2.0' ]

debug=1


def build_package(target):

	
	env = packaging.buildenv(target, print_output=debug)

	remote_temp = "/tmp/packaging"

	remote_strip_loc = env.info['jail_strip_path']

	output_dir = os.path.join("output", version, target, release) 

	if os.path.exists(output_dir):
		print "%s exists, bump release number" % output_dir
		sys.exit(1)

	temp_dir = "build" + os.sep + target
	unpacking_dir = temp_dir + os.sep + "temp"

	cwd = os.getcwd()

	if os.path.exists(temp_dir): shutil.rmtree(temp_dir)
	distutils.dir_util.mkpath(unpacking_dir)
	os.chdir(unpacking_dir)

	# Keep list of files used to build this package
	packages_used = []

	# Gotta do this here because rpm2cpio on solaris doesn't always work
	# Extract noarch rpms
	for package in rpm_packages_to_include[target]:
		package = packaging.package(env, package)
		latest_ver_dir = package.path + os.sep + utils.get_latest_ver(package.path)

		for file in os.listdir(latest_ver_dir):
			if not re.compile('\.spec').search(file):
				utils.extract_file(latest_ver_dir + os.sep + file, preserve_symlinks=1)
				packages_used += [ file ]


	print "Cleaning up"
	env.ssh.execute("rm -Rf %s; mkdir -p -m777 %s " % ( remote_temp, remote_temp))

	print "Copying files to remote..."
	env.ssh.copy_to("*", remote_temp, mode='tar');

	os.chdir(cwd)

	print "Installing mono to build env..."
	# Install the rest of mono

	# Get all files needed for the zip packages to include
	files = []
	for zip in zip_packages_to_include[target]:
		package = packaging.package(env, zip)
		files += package.get_files()
		files += package.get_dep_files()

	# Remove duplicates
	files = utils.remove_list_duplicates(files)

	packages_used += map(os.path.basename, files)
	packages_used.sort()

	# Also copy script to relocate and unpack the packages
	files += [config.packaging_dir + os.sep + 'do-install-zip-pkgs']
	
	# Copy them over...
	env.ssh.copy_to(files, '/tmp/install-packages', mode='scp', compress=0)

	# This will unpack and do all the substitution, including the noarch rpms
	env.ssh.print_output=debug
	env.ssh.execute("/tmp/install-packages/do-install-zip-pkgs %s /opt/mono /tmp/install-packages/* " % (remote_temp))

	# Strip files to save space
	env.ssh.execute("cd %s/bin; %s *; cd ../lib; %s * " % (remote_temp, remote_strip_loc, remote_strip_loc))
	env.ssh.print_output=debug

	print "Appending to startup environment..."
	# Add MONO_GAC_PREFIX to environment files
	# and rename env.sh to setup.sh

	# Probably don't need this anymore since we use /opt/mono as build prefix...
#	vars = {}
#	vars['MONO_GAC_PREFIX'] = '/opt/mono'
#	vars['MONO_PREFIX'] = '/opt/mono'
#	vars['MONO_CFG_DIR'] = '/opt/mono/etc'
#	vars['MONO_PATH'] = '/opt/mono/lib'
#
#	for k,v in vars.iteritems():
#		env.ssh.execute("cd %s; echo '%s=%s' >>  env.sh; echo 'setenv %s %s' >> env.csh" % (remote_temp, k, v, k, v))
#
#	env.ssh.execute("cd %s; export %s >>  env.sh" % (remote_temp, " ".join(vars.keys()) ) )
		
	# Rename environment files
	env.ssh.execute("cd %s; mv env.sh  setup.sh " % (remote_temp))
	env.ssh.execute("cd %s; mv env.csh setup.csh " % (remote_temp))


	# Print out packages_used
	print "Saving list of packages..."
	fd = open("%s/packages_used.txt" % temp_dir, 'w')
	for file in packages_used:
		fd.write(file + "\n")
	fd.close()

	# Start process of making the package

	# Create pkginfo
	print "Generate pkginfo and prototype files..."
	pkginfo_file = temp_dir + os.sep + "pkginfo"
	prototype_file = temp_dir + os.sep + "prototype"
	shutil.copy('pkginfo.template', pkginfo_file)

	#  Get some version information
	mono_package = packaging.package(env, 'mono')
	revision = mono_package.get_revision(release)

	# Get string of packages
	packages =  rpm_packages_to_include[target] + zip_packages_to_include[target]
	packages.sort()
	packages_string = " ".join( packages )

	parameter_map = {}
	parameter_map[re.compile("@@MONO_VERSION@@")] = version
	parameter_map[re.compile("@@MONO_RELEASE@@")] = revision
	parameter_map[re.compile("@@MONO_PACKAGES@@")] = packages_string
	utils.substitute_parameters_in_file(pkginfo_file, parameter_map)

	# Create prototype
	(code, prototype) = env.ssh.execute("cd %s; find . -print | pkgproto | sort" % remote_temp, capture_stderr=0 )

	#print prototype

	#Sample output: uid=104(builder) gid=1(other)
	(code, output) = env.ssh.execute("id")
	(uid, gid) = re.compile(r"""\((.*?)\).*\((.*?)\)""").search(output).groups()

	parameter_map = {}
	parameter_map[re.compile(uid)] = "root"
	parameter_map[re.compile(gid)] = "root"
	parameter_map[re.compile(" 0700 ")] = " 0755 "

	prototype = utils.substitute_parameters(prototype, parameter_map)

	# Add packages_used and ChangeLog
	prototype += "\nf none packages_used.txt\nf none ChangeLog"

	prototype = "i pkginfo\n" + prototype

	if os.path.exists(prototype_file): os.remove(prototype_file)

	fd = open(prototype_file, 'w')
	fd.write(prototype)
	fd.close()

	print "Copy pkginfo, prototype, packages_used, and ChangeLog to host..."
	# Use scp mode because we don't want paths to be included in the destination
	env.ssh.copy_to([pkginfo_file, prototype_file, temp_dir + os.sep + 'packages_used.txt', 'ChangeLog'], remote_temp, mode='scp')


	# Actually build the package
	print "Building package..."
	package_filename = "mono-%s_%s.%s.pkg" % (version, revision, env.info['arch'])
	(code, output) = env.ssh.execute("cd %s; pkgmk -d . -b \`pwd\`  &&  pkgtrans -s \`pwd\` %s all; gzip %s" % (remote_temp, package_filename, package_filename ))
	if code:
		print "%s: Error in creating package" % target
		sys.exit(1)

	distutils.dir_util.mkpath(output_dir)

	print "Copy package back..."
	# Have to use scp mode here, because I don't want the remote_temp dir in the filename
	# Also, use no compression, since file is already compressed
	env.ssh.copy_from("%s/%s.gz" % (remote_temp, package_filename), output_dir, mode='scp', compress=0)

	# Create md5
	print "Create md5..."
	utils.launch_process("cd %s; md5sum %s.gz > %s.gz.md5 " % (output_dir, package_filename, package_filename), print_output=debug)

	print "Saving packages_used.txt..."
	shutil.copy(temp_dir + os.sep + 'packages_used.txt', output_dir)




####  Main execution ####
# Collect args
if len(sys.argv) < 3:
	print "Usage: ./buildpackage <target> <version> [<release>]"
	print " target is the 'distro name', or 'all' for all solaris builds"
	print " Example: ./buildpackage sunos-8-sparc 1.1.13"
	sys.exit(1)

target = sys.argv[1]
version = sys.argv[2]

if len(sys.argv) > 3:
	release = sys.argv[3]
else:
	release = "0"


if target == 'all':
	targets = map(os.path.basename, glob.glob(config.packaging_dir + "/conf/sunos-*-*"))
else:
	targets = target.split(',')


# Starting build each target
threads = []
for target in targets:
	thread = threading.Thread(target=build_package, args=(target,))
	thread.run()
	
	threads.append(thread)


# Wait for all to finish
for thread in threads:
	if thread.isAlive(): thread.join()


